// <auto-generated />
using Hackathon_Greenhouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hackathon_Greenhouse.Migrations
{
    [DbContext(typeof(Hackathon_GreenhouseContext))]
    [Migration("20201201135954_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Hackathon_Greenhouse.Models.SensorData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("fan")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("high_light_intensity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("humidity")
                        .HasColumnType("REAL");

                    b.Property<bool>("isLightOn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("is_moist")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("pump")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("servo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("temp")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("SensorData");
                });
#pragma warning restore 612, 618
        }
    }
}
