// <auto-generated />
using Hackathon_Greenhouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hackathon_Greenhouse.Migrations
{
    [DbContext(typeof(Hackathon_GreenhouseContext))]
    partial class Hackathon_GreenhouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Hackathon_Greenhouse.Models.SensorData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("fan")
                        .HasColumnType("INTEGER");

                    b.Property<double>("fan_power")
                        .HasColumnType("REAL");

                    b.Property<double>("humidity")
                        .HasColumnType("REAL");

                    b.Property<string>("led_strip_matrix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("pump")
                        .HasColumnType("INTEGER");

                    b.Property<double>("pump_power")
                        .HasColumnType("REAL");

                    b.Property<double>("temp")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("SensorData");
                });
#pragma warning restore 612, 618
        }
    }
}
